spring:
  application:
    name: ec2-spring

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info,health
  info:
    env:
      enabled: true

info:
  team-name: ${team-name}

logging:
  level:
    root: INFO