spring:
  config:
    import: aws-parameterstore:/camp-health-app/prod/
  cloud:
    aws:
      s3:
        bucket: camp-profile-images-hwangsunnam
      region:
        static: ap-northeast-2

  datasource:
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}

team-name: ${team-name}

logging:
  level:
    io.awspring.cloud: DEBUG
    software.amazon.awssdk: DEBUG