spring:
  config:
    import: aws-parameterstore:/camp-health-app/prod/
  datasource:
    url: ${/camp-health-app/prod/db-url}
    username: ${db-username}
    password: ${db-password}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  team-name: ${team-name}